name: Deploy to Vercel

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel Production
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: team_I3SxbMVpxHbmSwpp0utQbYrq
          vercel-project-id: prj_h7ZpXXUnhQKiTM9YgAJTxzfO5WLH
          working-directory: ./
          vercel-args: "--prod"
